---
openvpn_install_packages:
  - easy-rsa
  - openvpn

openvpn_workdir: "/etc/openvpn"
openvpn_server_addr: ""
openvpn_server_name: "openvpn-server"
openvpn_server_subnet: "10.255.255.0 255.255.255.0"

openvpn_server_conf_local: 0.0.0.0
openvpn_server_conf_port: 443
openvpn_server_conf_proto: tcp
openvpn_server_conf_dev: tun
openvpn_server_conf_ca: /etc/openvpn/easy-rsa/pki/ca.crt
openvpn_server_conf_cert: "/etc/openvpn/easy-rsa/pki/issued/{{ openvpn_server_name }}.crt"
openvpn_server_conf_key: "/etc/openvpn/easy-rsa/pki/private/{{ openvpn_server_name }}.key"
openvpn_server_conf_dh: "/etc/openvpn/easy-rsa/pki/dh.pem"
openvpn_server_conf_topology: subnet
openvpn_server_conf_server: "{{ openvpn_server_subnet }}"
openvpn_server_conf_client_config_dir: ccd
openvpn_server_conf_push:
  - "redirect-gateway def1 bypass-dhcp"
  - "dhcp-option DNS 1.1.1.1"
  - "route 172.16.8.0 255.255.252.0"
openvpn_server_conf_duplicate_cn: duplicate-cn
openvpn_server_conf_keepalive: 10 120
openvpn_server_conf_cipher: AES-128-GCM
openvpn_server_conf_status: /var/log/openvpn/openvpn-status.log
openvpn_server_conf_log: /var/log/openvpn/openvpn.log
openvpn_server_conf_log_append: /var/log/openvpn/openvpn.log
openvpn_server_conf_verb: 4
openvpn_server_conf_explicit_exit_notify: 0
openvpn_server_conf_tun_mtu: 1400
