---
- name: Install packages
  loop: "{{ openvpn_install_packages }}"
  loop_control:
    loop_var: package
  ansible.builtin.package:
    name: "{{ package }}"
    state: "present"

- name: Enable system traffic forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Create scripts
  with_items:
    - create_client.sh
    - server_certs.sh
  loop_control:
    loop_var: script
  ansible.builtin.template:
    mode: "0755"
    src: "{{ script }}.j2"
    dest: "{{ openvpn_workdir }}/{{ script }}"

- name: Create server conf
  ansible.builtin.template:
    mode: "0644"
    src: "server.conf.j2"
    dest: "{{ openvpn_workdir }}/{{ openvpn_server_name }}.conf"
