---
- name: Install packages
  loop: "{{ openvpn_install_packages }}"
  loop_control:
    loop_var: package
  ansible.builtin.package:
    name: "{{ package }}"
    state: "present"

- name: Create a client-config directory if it does not exist
  ansible.builtin.file:
    path: "{{ openvpn_workdir }}/ccd"
    state: directory
    mode: '0755'

- name: Create scripts
  with_items:
    - create_client_user_pass.sh
    - create_client_cert.sh
    - server_certs.sh
    - auth.sh
  loop_control:
    loop_var: script
  ansible.builtin.template:
    mode: "0755"
    src: "{{ script }}.j2"
    dest: "{{ openvpn_workdir }}/{{ script }}"

- name: Create server conf
  ansible.builtin.template:
    mode: "0644"
    src: "server.conf.j2"
    dest: "{{ openvpn_workdir }}/{{ openvpn_server_name }}.conf"
  notify: Restart openvpn

- name: Generate systemd service unit
  ansible.builtin.template:
    src: "openvpn@.service.j2"
    dest: "/lib/systemd/system/openvpn@.service"
    mode: "0644"
  notify: Restart openvpn

- name: Start service
  ansible.builtin.systemd:
    name: "openvpn@{{ openvpn_server_name }}"
    state: started
    enabled: true
    daemon-reload: true
